### ISSUE TITLE
Allow cubit to override the provider

### ISSUE THREAD

**Issue by chimon2000** [felangel/cubit#19]
I would like to be able to override the dispose method on my Cubit.  My reason being that I need to kill a timer.  My workaround is to create the timer elsewhere and pass the cubit into the constructor.

**Comment by felangel** [comment]
Hi @chimon2000 👋 
Thanks for opening an issue!

Can you please provide a bit more context? You you can currently override `close` in your cubit and handle cancelling the timer there.

```dart
class CounterCubit extends Cubit<int> {
  @override
  Future<void> close() {
    // clean up stuff here
    return super.close();
  }
}
```

Let me know if that helps 👍

**Comment by chimon2000** [comment]
I was looking for dispose, so I missed this.  Thanks, closing this issue!
