### ISSUE TITLE
Why do we need to specify the cobit state type in the cubitBuilder?

### ISSUE THREAD

**Issue by pedromassango** [felangel/cubit#33]
Is there a chance to have this:

```
CubitBuilder<CubitA>(
  cubit: cubitA, // provide the local cubit instance
  builder: (context, state) {
    // return widget here based on CubitA's state
  }
)
```

 instead of:

```
CubitBuilder<CubitA, CubitAState>(
  cubit: cubitA, // provide the local cubit instance
  builder: (context, state) {
    // return widget here based on CubitA's state
  }
)
```

This can reduce the boilerplate of this package.
I think that it is possible to get the cobit state type from the cubit subclass.

**Comment by felangel** [comment]
Hi @pedromassango 👋
Thanks for opening an issue!

I would love to be able to do that but unfortunately I don’t think it’s possible (see https://github.com/felangel/bloc/issues/560).

Let me know if you know of a workaround 😄

**Comment by pedromassango** [comment]
Thanks for the response. Looks like this is a language restriction.
