### ISSUE TITLE
Cubit Delegate/Supervisor missing?

### ISSUE THREAD

**Issue by Manuelbaun** [felangel/cubit#34]
HI, 
I am new to your package Cubit and used previously the Bloc package. There is the supervisor, which you can utilize to debug etc.
Do you have it in Cubit as well, if not, how can I work around it?

Thanks again for your work!

**Comment by felangel** [comment]
Hi @Manuelbaun 👋
Thanks for opening an issue!

It has been renamed to `CubitObserver`.

You can initialize it 
```dart
via Cubit.observer = MyCubitObserver();
```

Hope that helps 👍
