### ISSUE TITLE
Provide a example in how to emit a complex object state

### ISSUE THREAD

**Issue by pedromassango** [felangel/cubit#35]
I'm trying to use Cubit this a complex state object and it is hard to emit state.

Here is my implementation:
```
@freezed
abstract class AuthState with _$AuthState {
  const factory AuthState({
    @Default(false) bool isLoggedIn,
  }) = _AuthState;
}

class AuthStateCubit extends Cubit<AuthState> {
  AuthStateCubit(this._preferences) : super(AuthState());

  final SharedPreferences _preferences;

  void updateLoginStatus() {
    state.copyWith.call(
      isLoggedIn: _preferences.getBool('_is_logged_in') ?? false;
    );
    emit(state);
  }
}
```
The idea here is to mantain the previous state and only update what have changed. Here it is almost implosible to emit a new state (inside the updateLoginStatus method). I can do: 
```
emit(state.copyWith.call(
        isLoggedIn: _preferences.getBool('_is_logged_in') ?? false
    ));
```
But this sintax doesn't look good and since I can't mutate the state property it is hard to do so. Do you have any suggestion?

**Comment by felangel** [comment]
Hi @pedromassango 👋 
Thanks for opening an issue!

How about something like:

```dart
void updateLoginStatus() {
  final newState = state.copyWith(
    isLoggedIn: _preferences.getBool('_is_logged_in') ?? false,
  );
  emit(newState);
}
```

You can also do it in one line like:

```dart
void updateLoginStatus() {
  emit(state.copyWith(isLoggedIn: _preferences.getBool('_is_logged_in') ?? false));
}
```

> But this sintax doesn't look good and since I can't mutate the state property it is hard to do so. Do you have any suggestion?

Not sure what you mean by this? It should be no different from yielding a new state within `mapEventToState` when using the bloc library. Can you please elaborate? Thanks 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions/details and I'm happy to continue the conversation 👍
