### ISSUE TITLE
CubitModule?

### ISSUE THREAD

**Issue by magillus** [felangel/cubit#43]
Hello, so far I love this - after reading this package's documentation.

I have question if it is worth to add a `CubitModule` that would combine with `MultiCubitProvider`.
It would have list of Cubits needed for a child, quite handy if common list of `CubitProvider` is used in many places.

```
MultiCubitProvider(
  providers: [
    CubitProvider<CubitA>(
      create: (BuildContext context) => CubitA(),
    ),
    CubitProvider<CubitB>(
      create: (BuildContext context) => CubitB(),
    ),
    CubitProvider<CubitC>(
      create: (BuildContext context) => CubitC(),
    ),
  ],
  child: ChildA(),
)
```
could be replaced with:
```
MultiCubitProvider(
  module: MyCubitModule(),
  child: ChildA(),
)
```

Optional the `modules` but that would require also check if same Cubit was not already provided in other module. 
After digging into source of this and Provider, that might be not worth adding.

Also this can be resolved with static list of providers, if their initialization and `create` method isn't called until needed.

**Comment by magillus** [comment]
Now as I see the callbacks to create the `CubitA`/`CubitB`/`CubitC` will not have options for current build `context`.

**Comment by felangel** [comment]
Hey @magillus 👋 
Thanks for opening an issue and for the positive feedback!

I've seen projects have their version of this by extracting the MultiProvider into a separate widget like:

```dart
class MyCubitModule extends MultiCubitProvider {
  MyCubitModule({@required Widget child}) : super(providers: [...], child: child);
}
```

Then you can use it in your widget tree like:

```dart
MyCubitModule(child: ChildA());
```

Let me know what you think and thanks again for opening an issue! 🙏

**Comment by magillus** [comment]
That sounds like a good solution, I didn't come with possibility, since myself not using provider much.
Thank you for explanation.
