### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by chimon2000** [felangel/cubit#45]
It would be nice if there were snippets for officially hosted IDEs - Android Studio and VS Code. 

I would expect the following to be covered:

- Cubit
- CubitObserver
- HydratedCubit
- MultiCubitListener
- CubitProvider
- CubitConsumer
- CubitBuilder
- CubitListener

**Comment by felangel** [comment]
Hey @chimon2000 👋
Thanks for opening an issue! I was planning to add support for them in the bloc vscode extension and should have a release later this evening 👍
