### ISSUE TITLE
Scale cubit with bloc capabilities

### ISSUE THREAD

**Issue by chimon2000** [felangel/cubit#6]
I posed this question on [Twitter](https://twitter.com/chimon1984/status/1268565830784233483?s=20) and wanted to document it here as an issue.

I like the idea of cubit as being the baseline for bloc.  It would allow teams to start with applications that don't need the event sourcing features that bloc provides, and scale up portions of their applications or the entire application when the need arises.

**Comment by felangel** [comment]
Hey @chimon2000 👋 
Thanks for bringing this back up.

I'd like to better understand what you envision the feature-set of cubit would be and what additional changes need to be made in order to achieve that. Thanks again! 😄

**Comment by chimon2000** [comment]
Sure, I have a very rudimentary understanding of how bloc works, but I would envision it working:

Bloc/CubitBloc

```
Bloc<Event, State> extends Cubit<State> implements Sink<Event> {

  /// Transforms events to states but uses emit(transition.nextState) instead of _stateController.add(transition.nextState)
  void _bindEventsToStates();
}
```

**Comment by felangel** [comment]
@chimon2000 would love your feedback on https://github.com/felangel/bloc/pull/1302 👍

**Comment by chimon2000** [comment]
Feedback given! Looks like it was awesomely simple.
