### ISSUE TITLE
Preserve intialState of a cubit

### ISSUE THREAD

**Issue by pedromassango** [felangel/cubit#62]
**Is your feature request related to a problem? Please describe.**
In many cases we need to reset our state to a "initial state" and currently we do this by passing a new value to override a property of our state.

For example, my state have a list of languages based on the selected Project so everytime I need to load languages from the new selected project I need to clear/reset my list of languages right before loading new languages based on the current selected project.

```dart
  Future loadLanguages(Project project) async {
    emit(state.copyWith.call(
      languages: [], // I need the initial state here
      isLoadingLanguages: true,
      loadLanguageFailure: null // I need the initial state here too
    ));

    final result = await languageRepository.getProjectLanguages(project.id);

    var newState = state.copyWith.call(isLoadingLanguages: false);

    newState = result.fold(
          (l) => newState.copyWith(loadLanguageFailure: l),
          (r) => newState.copyWith(languages: r),
    );
    emit(newState);
  }
```

**Describe the solution you'd like**
My suggestion is to let the Cubit preserve the initial state (something like `initialState` property) of a the cubit so that we don't need to create it everytime we need it.

**Comment by felangel** [comment]
Hi @pedromassango 👋 

You can add an `initialState` property to your `cubit` as needed 👍 

```dart
class CounterCubit extends Cubit<int> {
  CounterCubit(this.initialState) : super(initialState);

  final int initialState;
}
```

Hope that helps 👍

**Comment by pedromassango** [comment]
> Hi @pedromassango 👋
> 
> You can add an `initialState` property to your `cubit` as needed 👍
> 
> ```dart
> class CounterCubit extends Cubit<int> {
>   CounterCubit(this.initialState) : super(initialState);
> 
>   final int initialState;
> }
> ```
> 
> Hope that helps 👍

I mean, the cubit to preserve the initial state passed into it. The solution you suggested works but:

- You need to provide it via constructor
- You need to write a lot fo code for every Cubit in the project when neccessary.

**Comment by felangel** [comment]
What do you mean? It's one extra line of code haha. If you want, you can make your own custom cubit that does this for you like:

```dart
abstract class MyCubit<T> extends Cubit<T> {
  MyCubit(this.initialState) : super(initialState);
  final T initialState;
}
```

Then you can make your cubits all extend `MyCubit` instead:

```dart
class CounterCubit extends MyCubit<int> {
  CounterCubit() : super(0);

  void someMethod() {
    // you can now access the initial state via `initialState`
  }
}
```

This solution is the same amount of code as you would currently write minus the `MyCubit` class (which is a one time thing) 👍

**Comment by x1z7** [comment]
Hi @pedromassango 👋

It's not cubit's responsibility to cache your initial state.
You can have a factory constructor on your freezed data class

```
factory LanguageState.initial() => LanguageState(
      languages: [],
      isLoadingLanguages: true,
      loadLanguageFailure: null,
);
```
and use it to initialize your cubit or to emit it again when needed.

`LanguageCubit() : super(LanguageState.initial());`

`emit(LanguageState.initial());`

Hope that helps 👍

**Comment by pedromassango** [comment]
I get it 👍
