### ISSUE TITLE
What scopes API should look like?

### ISSUE THREAD

**Issue by orsenkucher** [felangel/cubit#67]
I'm always frustrated when I can't use my hydrated storage in multiple directories with multiple secure access keys at one project.

I've figured out all problems on roadmap to this feature except how to defer new scope creation, for example after user passed auth UI. 
And also how API should look? Give me your thoughts please🤗🤗

**Comment by felangel** [comment]
Haven't had enough time to focus on this but will think about it some more later this week. In the meantime it would be helpful if you could share a branch with your initial thoughts/attempt?

**Comment by orsenkucher** [comment]
Previously had some attempts written, but let's start from scratch and discuss things verbally for now
To come up with sorta RFC @felangel

**Comment by orsenkucher** [comment]
My first question would be: do we want single point of storage management for cubit and bloc?

**Comment by orsenkucher** [comment]
I suspect #69 answers ^this question hahaha

**Comment by felangel** [comment]
moved to https://github.com/felangel/bloc/issues/1428
