### ISSUE TITLE
Get state without builder

### ISSUE THREAD

**Issue by chimon2000** [felangel/cubit#7]
If possible, I'd envision this working similar to state_notifier, which exposes the state object as part of its provider and allows you to get the value using Provider.of or the provider context extensions.

https://github.com/rrousselGit/state_notifier/blob/eceb2d9ce0091b53a5d4c23336daf5fd35a6673d/packages/flutter_state_notifier/example/lib/main.dart#L82-L85

**Comment by felangel** [comment]
Hi @chimon2000 👋 
Thanks for opening an issue!

You can currently access the state of a cubit via the `state` property. For example, in a Flutter app, you can access the current cubit via `context.cubit` and then read the state property like:

```dart
context.cubit<CounterCubit>().state
```

Let me know if that helps 👍

**Comment by chimon2000** [comment]
Cool I saw that property but I wasn't sure if it was supposed to be used in that way.
